<a href="https://colab.research.google.com/github/LucasDiasFortes/Ciencia_Dados_Aprendizagem_Maquina/blob/main/Capitulo2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**# Nome: Lucas Dias| UDF | Sistemas de Informação| Ciencia de dados**



Manipulação de Dados Tabulares com Pandas - Funções Básicas

Tipos de Dados com Pandas

Renomeando Colunas

Selecionando Linhas e Colunas

Adicionando e Removendo Colunas

Operações Básicas - Consultas

Operações Básicas - Ordenação

Operações Básicas - Combinando DataFrames

Operações Básicas - Salvando DataFrames

In [ ]:
import pandas as pd

In [ ]:
cidades = pd.DataFrame(
    [
        ['Paraná','Londrina',575377,1356.00],
        ['São Paulo','São Carlos',254484,1508.00],
        ['Santa Catariana','Florianópolis',508826, 1798.00],
        ['Paraná','Curitiba', 1963726,2293.00],
        ['São Paulo','Campinas', 1223237, 1710.00]
    ], columns=['Estado','Cidade', 'Habitantes','Salario-Medio' ])
cidades

            Estado         Cidade  Habitantes  Salario-Medio
0           Paraná       Londrina      575377         1356.0
1        São Paulo     São Carlos      254484         1508.0
2  Santa Catariana  Florianópolis      508826         1798.0
3           Paraná       Curitiba     1963726         2293.0
4        São Paulo       Campinas     1223237         1710.0

In [ ]:
cidades.head(2)

      Estado      Cidade  Habitantes  Salario-Medio
0     Paraná    Londrina      575377         1356.0
1  São Paulo  São Carlos      254484         1508.0

In [ ]:
cidades.tail(2)

      Estado    Cidade  Habitantes  Salario-Medio
3     Paraná  Curitiba     1963726         2293.0
4  São Paulo  Campinas     1223237         1710.0

In [ ]:
cidades.shape # Retorna uma tupla com o número de linhas e colunas

(5, 4)

In [ ]:
cidades.columns # Retorna uma lista com o nome de todas as colunas

Index(['Estado', 'Cidade', 'Habitantes', 'Salario-Medio'], dtype='object')

In [ ]:
cidades['Salario-Medio'].describe() # Retorna um objeto DataFrame com as medidas estatísticas para cada coluna

count       5.000000
mean     1733.000000
std       357.459089
min      1356.000000
25%      1508.000000
50%      1710.000000
75%      1798.000000
max      2293.000000
Name: Salario-Medio, dtype: float64